# Podfile - 极简版

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks! :linkage => :static  # 关键修改！

target 'SwiftStudy2026' do
  pod 'RxSwift', '6.5.0'  # 使用确切版本
  pod 'RxCocoa', '6.5.0'
  
  pod 'SnapKit', '~> 5.0'
end
